### ISSUE TITLE
bundle install 수행 시 오류

### ISSUE THREAD

**Issue by min9nim** [madup-inc/madup-inc.github.io#31]
아래와 같은 오류 발생.
문제 원인 모르겠음 ㅠ

```
 madup-inc.github.io git:(master) bundle install       
Ignoring commonmarker-0.17.9 because its extensions are not built. Try: gem pristine commonmarker --version 0.17.9
Ignoring eventmachine-1.2.7 because its extensions are not built. Try: gem pristine eventmachine --version 1.2.7
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring nokogiri-1.8.4 because its extensions are not built. Try: gem pristine nokogiri --version 1.8.4
Ignoring sassc-2.2.1 because its extensions are not built. Try: gem pristine sassc --version 2.2.1
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using bundler 2.3.11
Using colorator 1.1.0
Using faraday-em_http 1.0.0
Using public_suffix 4.0.6
Using faraday-excon 1.1.0
Using faraday-httpclient 1.0.1
Using faraday-net_http 1.0.1
Using faraday-net_http_persistent 1.2.0
Using faraday-em_synchrony 1.0.0
Using faraday-patron 1.0.0
Using multipart-post 2.1.1
Using faraday-rack 1.0.0
Fetching http_parser.rb 0.8.0
Fetching eventmachine 1.2.7
Using ruby2_keywords 0.0.5
Using liquid 4.0.3
Using mercenary 0.3.6
Using safe_yaml 1.0.5
Using webrick 1.7.0
Using rb-fsevent 0.11.1
Using kramdown 1.17.0
Using faraday-retry 1.0.3
Using rouge 2.2.1
Using forwardable-extended 2.6.0
Fetching ffi 1.15.5
Using jekyll-paginate 1.1.0
Using pathutil 0.16.2
Using faraday-multipart 1.0.3
Using addressable 2.8.0
Using faraday 1.10.0
Using sawyer 0.8.2
Using octokit 4.22.0
Using jekyll-gist 1.5.0
Installing http_parser.rb 0.8.0 with native extensions
Installing eventmachine 1.2.7 with native extensions
Installing ffi 1.15.5 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/eventmachine-1.2.7/ext
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20220408-82075-92kove.rb extconf.rb
checking for -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME)
        --with-ssl-dir
        --without-ssl-dir
        --with-ssl-include
        --without-ssl-include=${ssl-dir}/include
        --with-ssl-lib
        --without-ssl-lib=${ssl-dir}/lib
        --with-openssl-config
        --without-openssl-config
        --with-pkg-config
        --without-pkg-config
        --with-cryptolib
        --without-cryptolib
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:546:in `block in try_link0'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:543:in `try_link0'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:789:in `try_func'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1016:in `block in have_library'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1011:in `have_library'
        from extconf.rb:8:in `block in check_libs'
        from extconf.rb:8:in `all?'
        from extconf.rb:8:in `check_libs'
        from extconf.rb:95:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-20/2.6.0/eventmachine-1.2.7/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/eventmachine-1.2.7 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-20/2.6.0/eventmachine-1.2.7/gem_make.out

  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:99:in `run'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:47:in `block in build'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:29:in `build'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:185:in `block in build_extension'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:181:in `build_extension'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:229:in `block in build_extensions'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:226:in `each'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:226:in `build_extensions'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/installer.rb:830:in `build_extensions'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/source/rubygems.rb:204:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/worker.rb:62:in `apply_func'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/worker.rb:57:in `block in process_queue'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/worker.rb:54:in `loop'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/worker.rb:54:in `process_queue'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing eventmachine (1.2.7), and Bundler cannot continue.

In Gemfile:
  jekyll-livereload was resolved to 0.2.2, which depends on
    em-websocket was resolved to 0.5.3, which depends on
      eventmachine
➜  madup-inc.github.io git:(master) 



➜  madup-inc.github.io git:(master) jekyll serve
Traceback (most recent call last):
        12: from /usr/local/bin/jekyll:23:in `<main>'
        11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
        10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `synchronize'
         9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:304:in `block in activate_bin_path'
         8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
         7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
         6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
         5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
         4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
         3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
         2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
         1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'http_parser.rb' (~> 0.6.0) among 172 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/mac9/.gem/ruby/2.6.0:/Library/Ruby/Gems/2.6.0:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0', execute `gem env` for more information
➜  madup-inc.github.io git:(master) 

```

**Comment by min9nim** [comment]
```
Could not find 'http_parser.rb' (~> 0.6.0)
```
요 메세지를 주의 깊게 보면 http_parser.rb 가 설치가 되어 있지 않은 모양이다.

해당 모듈만 단독으로 설치를 시도해 보았으나 아래와 같은 오류를 만남
```
 ➜  madup-inc.github.io git:(master) gem install http_parser.rb
Ignoring commonmarker-0.17.9 because its extensions are not built. Try: gem pristine commonmarker --version 0.17.9
Ignoring eventmachine-1.2.7 because its extensions are not built. Try: gem pristine eventmachine --version 1.2.7
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring nokogiri-1.8.4 because its extensions are not built. Try: gem pristine nokogiri --version 1.8.4
Ignoring sassc-2.2.1 because its extensions are not built. Try: gem pristine sassc --version 2.2.1
Building native extensions. This could take a while...
ERROR:  Error installing http_parser.rb:
        ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/http_parser.rb-0.8.0/ext/ruby_http_parser
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20220408-86920-11vwwrs.rb extconf.rb
creating Makefile

current directory: /Library/Ruby/Gems/2.6.0/gems/http_parser.rb-0.8.0/ext/ruby_http_parser
make "DESTDIR=" clean

current directory: /Library/Ruby/Gems/2.6.0/gems/http_parser.rb-0.8.0/ext/ruby_http_parser
make "DESTDIR="
make: *** No rule to make target `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin20/ruby/config.h', needed by `ruby_http_parser.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/http_parser.rb-0.8.0 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-20/2.6.0/http_parser.rb-0.8.0/gem_make.out
➜  madup-inc.github.io git:(master) 

```

아래 글을 보고 앱스트어 통해서 xCode 를 다시 설치해 보는 중..
https://seizemymoment.tistory.com/33

**Comment by min9nim** [comment]
xCode 를 다시 설치하니 위 오류는 없어짐!

그런데.. `jekyll serve` 수행시 다음과 같은 오류 발생
```

➜  madup-inc.github.io git:(master) ✗ jekyll serve
Ignoring sassc-2.2.1 because its extensions are not built. Try: gem pristine sassc --version 2.2.1
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring commonmarker-0.17.9 because its extensions are not built. Try: gem pristine commonmarker --version 0.17.9
Ignoring ffi-1.11.3 because its extensions are not built. Try: gem pristine ffi --version 1.11.3
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring nokogiri-1.8.4 because its extensions are not built. Try: gem pristine nokogiri --version 1.8.4
Traceback (most recent call last):
        10: from /usr/local/bin/jekyll:23:in `<main>'
         9: from /usr/local/bin/jekyll:23:in `load'
         8: from /Library/Ruby/Gems/2.6.0/gems/jekyll-4.0.0/exe/jekyll:11:in `<top (required)>'
         7: from /Library/Ruby/Gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
         6: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler.rb:151:in `setup'
         5: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/runtime.rb:24:in `setup'
         4: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/runtime.rb:24:in `map'
         3: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/spec_set.rb:136:in `each'
         2: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/spec_set.rb:136:in `each'
         1: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/runtime.rb:25:in `block in setup'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/runtime.rb:309:in `check_for_activated_spec!': You have already activated jekyll-sass-converter 2.0.1, but your Gemfile requires jekyll-sass-converter 1.5.2. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
➜  madup-inc.github.io git:(master) ✗ 

```

**Comment by min9nim** [comment]
WoW!

이제 `bundle exec jekyll serve` 로 실행시키니까 된다!

![image](https://user-images.githubusercontent.com/6068828/162422003-83f579a3-a2d3-413b-9127-8e162825b339.png)
